# Generated by Django 4.0.4 on 2022-05-02 20:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamHelper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myUUID', models.UUIDField(default=uuid.uuid4)),
                ('user', models.CharField(max_length=30)),
                ('descr', models.CharField(default='descr', max_length=30)),
                ('name', models.CharField(default='somename', max_length=20)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
